export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_HAS_ASSOCIATIONS: "DOCUMENT_HAS_ASSOCIATIONS",
  DUPLICATE_ACTIVE_TITLE: "DUPLICATE_ACTIVE_TITLE"
} as const;
