export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DUPLICATE_ACTIVE_TITLE: "DUPLICATE_ACTIVE_TITLE",
  DOCUMENT_HAS_RELATIONS: "DOCUMENT_HAS_RELATIONS",
  ARCHIVED_READ_ONLY: "ARCHIVED_READ_ONLY"
} as const;
